#!/bin/bash
# Adds all standard remotes for the repository.
# Usage:
#   git iree-setup-remotes
#
# Does nothing if a remote already exists.
source "$(dirname $0)/bash_script_setup.sh"

function add_remote() {
  local remote_name="$1"
  local head="${2-main}"
  local fetch_url="$3"
  local push_url="${4-${fetch_url}}"
  local existing_url
  existing_url="$(git remote get-url ${remote_name} 2>/dev/null || true)"
  if [ -z "${existing_url}" ]; then
    echo "Adding new remote ${remote_name} -> ${fetch_url} (push ${push_url})"
    git remote add -m "${head}" --no-tags "${remote_name}" "${fetch_url}"
    git remote set-url --push "${remote_name}" "${push_url}"
  else
    echo "Skipping remote ${remote_name} (already exists)"
  fi
}

add_remote iree-upstream main \
  https://github.com/google/iree.git git@github.com:google/iree.git
add_remote llvm-project-upstream main \
  https://github.com/llvm/llvm-project.git git@github.com:llvm/llvm-project.git
add_remote mlir-hlo-upstream master \
  https://github.com/tensorflow/mlir-hlo.git git@github.com:tensorflow/mlir-hlo.git
add_remote mlir-npcomp main \
  https://github.com/llvm/mlir-npcomp.git git@github.com:llvm/mlir-npcomp.git
